//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-09-11 09:49:39 AuthBy:cmm
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace DataEntity
{	
	[Table("Sys_role")] 
	public partial class Sys_roleEntity
    {
		#region 属性
				
		/// <summary>
		/// 
		/// </summary>	
		[Key] 
		 
		 
		[Display(Name = "")]
		 
		public string RoleCode { get; set; }
				
		/// <summary>
		/// 
		/// </summary>	
		 
		 
		[StringLength(10)] 
		[Display(Name = "")]
		 
		public string RoleSeq { get; set; }
				
		/// <summary>
		/// 
		/// </summary>	
		 
		 
		[StringLength(200)] 
		[Display(Name = "")]
		 
		public string RoleName { get; set; }
				
		/// <summary>
		/// 
		/// </summary>	
		 
		 
		[StringLength(2048)] 
		[Display(Name = "")]
		 
		public string Description { get; set; }
				
		/// <summary>
		/// 
		/// </summary>	
		 
		 
		[StringLength(20)] 
		[Display(Name = "")]
		 
		public string CreatePerson { get; set; }
				
		/// <summary>
		/// 
		/// </summary>	
		 
		 
		 
		[Display(Name = "")]
		[DataType(DataType.DateTime)] 
		public DateTime CreateDate { get; set; }
				
		/// <summary>
		/// 
		/// </summary>	
		 
		 
		[StringLength(20)] 
		[Display(Name = "")]
		 
		public string UpdatePerson { get; set; }
				
		/// <summary>
		/// 
		/// </summary>	
		 
		 
		 
		[Display(Name = "")]
		[DataType(DataType.DateTime)] 
		public DateTime UpdateDate { get; set; }
		 
      #endregion

	   	#region 设置默认值
		///<summary>
		///set default value
		///</summary>
		public void SetDefaultValue()
		{
						if (this.RoleCode == null) this.RoleCode = "";
			if (this.RoleSeq == null) this.RoleSeq = "";
			if (this.RoleName == null) this.RoleName = "";
			if (this.Description == null) this.Description = "";
			if (this.CreatePerson == null) this.CreatePerson = "";
			if (this.CreateDate.Year<1900) this.CreateDate =  new DateTime(1900,01,01);
			if (this.UpdatePerson == null) this.UpdatePerson = "";
			if (this.UpdateDate.Year<1900) this.UpdateDate =  new DateTime(1900,01,01);

		}
		#endregion

		#region 字段
		public static class Fields
		{ 
			public const string DataBaseName= "ItemManage";

			public const string TableName = "dbo.Sys_role";

	   		public const string RoleCode = "RoleCode";
	   
	   		public const string RoleSeq = "RoleSeq";
	   
	   		public const string RoleName = "RoleName";
	   
	   		public const string Description = "Description";
	   
	   		public const string CreatePerson = "CreatePerson";
	   
	   		public const string CreateDate = "CreateDate";
	   
	   		public const string UpdatePerson = "UpdatePerson";
	   
	   		public const string UpdateDate = "UpdateDate";
	   
	   	  }
		#endregion

		#region	基本SQL
        public static class Sql 
        {
		   
		    //所有字段组成的字符串,逗号分隔
		    public static string PartSqlFields=" RoleCode,RoleSeq,RoleName,Description,CreatePerson,CreateDate,UpdatePerson,UpdateDate"; 

			//From后面部分的Sql语句
		    public static string PartAfterFromSql=" ItemManage.dbo.Sys_role  WITH(NOLOCK) WHERE 1=1 "; 
			
			//查询sql
			public static string SqlDetail="SELECT RoleCode,RoleSeq,RoleName,Description,CreatePerson,CreateDate,UpdatePerson,UpdateDate FROM ItemManage.dbo.Sys_role  WITH(NOLOCK) WHERE 1=1  ";
        }
		#endregion
    }
}

